server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: order-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      group-id: order-service
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
app:
  topic:
    name: order-events